### ISSUE TITLE
Size error when packing SOL object value

### ISSUE THREAD

**Issue by keomabrun** [realms-team/sol#26]
```
=== traceback ===
Traceback (most recent call last):
  File "solmanager.py", line 758, in run
    self.publishNow()
  File "solmanager.py", line 836, in publishNow
    solBinObjectsToPublish = [self.sol.json_to_bin(o) for o in self.solJsonObjectsToPublish]
  File "/home/pi/solmanager/../sol/Sol.py", line 153, in json_to_bin
    sol_json['value']
  File "/home/pi/solmanager/../sol/Sol.py", line 546, in _fields_to_binary_with_structure
    returnVal       = [ord(b) for b in struct.pack(pack_format,*pack_values)]
error: integer out of range for 'H' format code
```

**Comment by keomabrun** [comment]
Arise when temperature below 0
