### ISSUE TITLE
NotImplemented Error

### ISSUE THREAD

**Issue by keomabrun** [realms-team/sol#30]
CRASH in Thread DustThread!

=== exception type ===
<type 'exceptions.NotImplementedError'>

=== traceback ===
Traceback (most recent call last):
  File "solmanager.py", line 555, in _notifAll
    macManager = self.macManager,
  File "/home/keoma/Documents/REALMS/solmanager/../sol/Sol.py", line 99, in dust_to_json
    (sol_type,sol_value) = self._get_sol_json_value(dust_notif)
  File "/home/keoma/Documents/REALMS/solmanager/../sol/Sol.py", line 552, in _get_sol_json_value
    raise NotImplementedError()
NotImplementedError

**Comment by keomabrun** [comment]
Issue move to solmanager
[https://github.com/realms-team/solmanager/issues/48](https://github.com/realms-team/solmanager/issues/48)
