### ISSUE TITLE
Crash when parsing dust hr

### ISSUE THREAD

**Issue by keomabrun** [realms-team/sol#35]
CRASH in Thread DustThread!

=== exception type ===
<type 'exceptions.AssertionError'>

=== traceback ===
Traceback (most recent call last):
  File "solmanager.py", line 535, in _notifAll
    macManager = self.macManager,
  File "/home/realms/solmanager/../sol/Sol.py", line 99, in dust_to_json
    (sol_type,sol_value) = self._get_sol_json_value(dust_notif)
  File "/home/realms/solmanager/../sol/Sol.py", line 551, in _get_sol_json_value
    (sol_type,sol_value) = self._get_sol_json_value_dust_hr(dust_notif)
  File "/home/realms/solmanager/../sol/Sol.py", line 686, in _get_sol_json_value_dust_hr
    assert 'Discovered' not in hr
AssertionError

**Comment by keomabrun** [comment]
@twatteyne 
I don't get why we use assertions for HR on function  _get_sol_json_value_dust_hr line (line 680)
https://github.com/realms-team/sol/blob/develop/Sol.py#L680

**Comment by twatteyne** [comment]
This is to make sure an HR frame contains only a single HR type. Maybe
wrong with our rework?

**Comment by keomabrun** [comment]
This comes the fact that HR_Devices are not properly spitted by the solmanager.
See https://github.com/realms-team/solmanager/issues/56
