### ISSUE TITLE
json_to_bin fails when mac field is a string

### ISSUE THREAD

**Issue by keomabrun** [realms-team/sol#67]
The `json_to_bin` function should do one of the two following suggestion for the `mac` field:
* allow both `list` and `str` type
* assert `list` type

Corresponding code:
https://github.com/realms-team/sol/blob/master/solobjectlib/Sol.py#L144

The following error appears on the Botanical Garden site:
```
CRASH
Thread PubServerThread!

=== exception type ===
<type 'exceptions.TypeError'>

=== traceback ===
Traceback (most recent call last):
  File "solmanager.py", line 113, in run
    self._doSomething()
  File "solmanager.py", line 318, in _doSomething
    self._publishNow()
  File "solmanager.py", line 412, in _publishNow
    http_payload.append(self.sol.bin_to_http(chunk))
  File "/root/solmanager/../sol/solobjectlib/Sol.py", line 190, in bin_to_http
    "o":    [base64.b64encode(s) for s in ("".join(chr(b) for b in sol_bin) for sol_bin in sol_binl)]
  File "/root/solmanager/../sol/solobjectlib/Sol.py", line 190, in <genexpr>
    "o":    [base64.b64encode(s) for s in ("".join(chr(b) for b in sol_bin) for sol_bin in sol_binl)]
  File "/root/solmanager/../sol/solobjectlib/Sol.py", line 190, in <genexpr>
    "o":    [base64.b64encode(s) for s in ("".join(chr(b) for b in sol_bin) for sol_bin in sol_binl)]
TypeError: an integer is required
```

**Comment by keomabrun** [comment]
Same kind of error when publishing json to MQTT
```
CRASH

=== exception type ===
<type 'exceptions.TypeError'>

=== traceback ===
Traceback (most recent call last):
  File "solmanager.py", line 185, in _handler_dust_notifs
    WastonIotThread().publish(sol_json)  # to the mqtt server over the Internet
  File "solmanager.py", line 505, in publish
    FormatUtils.formatBuffer(sol_object["mac"]),
  File "/root/solmanager/../smartmeshsdk/libs/SmartMeshSDK/utils/FormatUtils.py", line 11, in format
Buffer
    return '-'.join(["%.2x"%i for i in buf])
TypeError: %x format: a number is required, not unicode
```
